// @opennextjs/cloudflare's getCloudflareContext() returns env typed as the
// global `CloudflareEnv` interface (declared inside that package, covering
// only ITS OWN internal bindings like ASSETS/caching). It does NOT
// automatically pick up our own bindings from wrangler.jsonc — those land in
// a separate global `Env` interface, generated by `wrangler types` into
// worker-configuration.d.ts. This file merges the two via TypeScript
// declaration merging, so `env.DB` in src/lib/db.ts actually type-checks.
//
// Re-run `npm run cf:typegen` after changing wrangler.jsonc's bindings, then
// this file picks up the change automatically — nothing here needs editing.
declare global {
  // eslint-disable-next-line @typescript-eslint/no-empty-object-type -- intentional: this merges Env's members into CloudflareEnv via declaration merging
  interface CloudflareEnv extends Env {}
}

export {};
