import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({ baseDirectory: import.meta.dirname });

const eslintConfig = [
  {
    ignores: [
      "worker-configuration.d.ts", // generated by `wrangler types` — never hand-edited
      ".next/**",
      ".open-next/**",
      "src/generated/**", // generated by `prisma generate`
      "next-env.d.ts", // generated by Next.js
      "coverage/**",
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript", "prettier"),
];

export default eslintConfig;
